"""Experiment logging, metric export, and checkpoint management.

Provides structured JSONL event tracking, console progress summaries,
CSV/Excel tabular exports, and PyTorch model checkpoint persistence.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union
import csv
import json
import logging
import os
import time
import numpy as np
import pandas as pd
import torch

logger = logging.getLogger("riscmal")


class IncrementalExperimentLogger:
    """Central experiment logger supporting JSONL, CSV, and multi-sheet Excel logging."""

    def __init__(
        self,
        output_dir: Union[str, Path] = "results",
        excel_path: Optional[Union[str, Path]] = None,
        jsonl_filename: str = "experiment_metrics.jsonl",
        csv_filename: str = "experiment_metrics.csv",
    ) -> None:
        """Initializes the experiment logger and ensures destination directories exist.

        Args:
            output_dir: Directory where logs and metrics are exported.
            excel_path: Optional explicit path to an Excel workbook (.xlsx).
            jsonl_filename: Name of structured JSONL metrics file.
            csv_filename: Name of flat CSV metrics file.
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.jsonl_path = self.output_dir / jsonl_filename
        self.csv_path = self.output_dir / csv_filename
        self.excel_path = Path(excel_path) if excel_path else self.output_dir / "malware_incremental_results.xlsx"

    def log_jsonl(self, record: Dict[str, Any]) -> None:
        """Appends a single structured JSON record to the JSONL log file.

        Args:
            record: Dictionary of serializable event/metric data.
        """
        # Convert any numpy or torch types to native python
        sanitized = self._sanitize_record(record)
        sanitized["timestamp"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        with open(self.jsonl_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(sanitized) + "\n")

    def log_csv(self, row_dict: Dict[str, Any]) -> None:
        """Appends a single dictionary row to the flat CSV log file.

        Args:
            row_dict: Flat dictionary of metric keys and numerical/string values.
        """
        sanitized = self._sanitize_record(row_dict)
        file_exists = self.csv_path.exists()
        fieldnames = list(sanitized.keys())

        with open(self.csv_path, "a", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            if not file_exists:
                writer.writeheader()
            writer.writerow(sanitized)

    def log_comprehensive_epoch(
        self,
        scenario_name: str,
        task_id: int,
        epoch: int,
        train_loss: float,
        train_acc: float,
        overall_report: Dict[str, Any],
        param_count: Optional[int] = None,
        epoch_time_sec: Optional[float] = None,
        peak_gpu_mb: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Logs comprehensive epoch metrics across all tracking modalities (Console, JSONL, CSV, Excel).

        Args:
            scenario_name: Name of continual learning method/strategy (e.g. 'RISC-Mal_S42').
            task_id: Current continual task index (1-based).
            epoch: Current training epoch within the task (1-based).
            train_loss: Average training loss for the epoch.
            train_acc: Training classification accuracy [0.0, 1.0].
            overall_report: Evaluation report dictionary generated by evaluation.metrics.
            param_count: Total trainable or total parameter count.
            epoch_time_sec: Execution duration of the epoch in seconds.
            peak_gpu_mb: Peak allocated GPU memory in MB.

        Returns:
            The assembled row dictionary.
        """
        row_data: Dict[str, Any] = {
            "Method": scenario_name,
            "Task_ID": int(task_id),
            "Epoch": int(epoch),
            "Train_Loss": round(float(train_loss), 6),
            "Train_Acc": round(float(train_acc), 6),
            "Overall_Accuracy": round(float(overall_report.get("accuracy", 0.0)), 6),
            "Macro_Precision": round(float(overall_report.get("macro_precision", 0.0)), 6),
            "Macro_Recall": round(float(overall_report.get("macro_recall", 0.0)), 6),
            "Macro_F1": round(float(overall_report.get("macro_f1", 0.0)), 6),
            "Weighted_Precision": round(float(overall_report.get("weighted_precision", 0.0)), 6),
            "Weighted_Recall": round(float(overall_report.get("weighted_recall", 0.0)), 6),
            "Weighted_F1": round(float(overall_report.get("weighted_f1", 0.0)), 6),
            "Micro_Precision": round(float(overall_report.get("micro_precision", 0.0)), 6),
            "Micro_Recall": round(float(overall_report.get("micro_recall", 0.0)), 6),
            "Micro_F1": round(float(overall_report.get("micro_f1", 0.0)), 6),
            "Worst_Class_Recall": round(float(overall_report.get("worst_class_recall", 0.0)), 6),
            "Average_Forgetting": round(float(overall_report.get("avg_forgetting", 0.0)), 6),
            "Old_F1": round(float(overall_report.get("old_f1", 0.0)), 6),
            "New_F1": round(float(overall_report.get("new_f1", 0.0)), 6),
            "Harmonic_Mean": round(float(overall_report.get("harmonic_mean", 0.0)), 6),
        }

        if param_count is not None:
            row_data["Param_Count"] = int(param_count)
        if epoch_time_sec is not None:
            row_data["Epoch_Time_Sec"] = round(float(epoch_time_sec), 4)
        if peak_gpu_mb is not None:
            row_data["Peak_GPU_MB"] = round(float(peak_gpu_mb), 2)

        # Append per-class metrics if available
        per_class = overall_report.get("per_class", {})
        for cls_key, cls_metrics in per_class.items():
            if isinstance(cls_metrics, dict):
                row_data[f"Class{cls_key}_Recall"] = round(float(cls_metrics.get("recall", 0.0)), 6)
                row_data[f"Class{cls_key}_F1"] = round(float(cls_metrics.get("f1-score", 0.0)), 6)
                row_data[f"Class{cls_key}_Precision"] = round(float(cls_metrics.get("precision", 0.0)), 6)

        # 1. Structured JSONL Log
        self.log_jsonl(row_data)

        # 2. Flat CSV Log
        try:
            self.log_csv(row_data)
        except Exception as e:
            logger.debug("Failed to write to CSV log: %s", e)

        # 3. Excel Multi-sheet Log
        self._append_excel(scenario_name, row_data)

        return row_data

    def _append_excel(self, sheet_name: str, row_data: Dict[str, Any]) -> None:
        """Appends row data to an Excel sheet."""
        try:
            df_new = pd.DataFrame([row_data])
            if not self.excel_path.exists():
                all_sheets: Dict[str, pd.DataFrame] = {}
            else:
                all_sheets = pd.read_excel(self.excel_path, sheet_name=None)

            clean_sheet = sheet_name[:31]  # Excel sheet names max 31 chars
            if clean_sheet in all_sheets:
                all_sheets[clean_sheet] = pd.concat([all_sheets[clean_sheet], df_new], ignore_index=True)
            else:
                all_sheets[clean_sheet] = df_new

            self.excel_path.parent.mkdir(parents=True, exist_ok=True)
            with pd.ExcelWriter(self.excel_path, engine="openpyxl", mode="w") as writer:
                for s_name, df_sheet in all_sheets.items():
                    df_sheet.to_excel(writer, sheet_name=s_name, index=False)
        except Exception as exc:
            # Excel export is best-effort (e.g. if file is locked or openpyxl missing)
            logger.debug("Excel append failed: %s", exc)

    @staticmethod
    def _sanitize_record(obj: Any) -> Any:
        """Recursively sanitizes data types for serialization."""
        if isinstance(obj, dict):
            return {k: IncrementalExperimentLogger._sanitize_record(v) for k, v in obj.items() if k not in ("all_true", "all_pred")}
        elif isinstance(obj, (list, tuple)):
            return [IncrementalExperimentLogger._sanitize_record(x) for x in obj]
        elif isinstance(obj, (np.floating, float)):
            return float(obj)
        elif isinstance(obj, (np.integer, int)):
            return int(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, torch.Tensor):
            return obj.detach().cpu().item() if obj.numel() == 1 else obj.detach().cpu().tolist()
        return obj


def save_system_checkpoint(
    model: torch.nn.Module,
    task_id: int,
    scenario_name: str,
    output_dir: Union[str, Path] = "checkpoints",
    metadata: Optional[Dict[str, Any]] = None,
) -> Path:
    """Saves a model checkpoint along with metadata.

    Args:
        model: PyTorch module whose state dictionary is saved.
        task_id: Continual learning task identifier.
        scenario_name: Strategy or scenario name.
        output_dir: Directory where the checkpoint file is written.
        metadata: Optional dictionary with task stats, hyperparameters, or training logs.

    Returns:
        Path to the saved checkpoint file.
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    save_path = out_dir / f"{scenario_name}_task{task_id}_checkpoint.pth"

    checkpoint_payload: Dict[str, Any] = {
        "task_id": task_id,
        "scenario_name": scenario_name,
        "model_state_dict": model.state_dict(),
        "metadata": metadata or {},
    }
    torch.save(checkpoint_payload, save_path)
    return save_path


def load_system_checkpoint(
    model: torch.nn.Module,
    checkpoint_path: Union[str, Path],
    device: Union[torch.device, str] = "cpu",
    strict: bool = True,
) -> Dict[str, Any]:
    """Loads a saved checkpoint into an existing model.

    Args:
        model: Target PyTorch module.
        checkpoint_path: Path to .pth checkpoint file.
        device: Device to load tensors onto.
        strict: Whether to strictly enforce matching state_dict keys.

    Returns:
        The metadata dictionary stored inside the checkpoint payload.
    """
    path = Path(checkpoint_path)
    if not path.is_file():
        raise FileNotFoundError(f"Checkpoint file not found: {checkpoint_path}")

    target_device = torch.device(device) if isinstance(device, str) else device
    payload = torch.load(path, map_location=target_device)

    if isinstance(payload, dict) and "model_state_dict" in payload:
        model.load_state_dict(payload["model_state_dict"], strict=strict)
        return payload.get("metadata", {})
    else:
        # Direct state dict
        model.load_state_dict(payload, strict=strict)
        return {}


def setup_logger(name: str = "riscmal") -> logging.Logger:
    """Configures and returns a standard formatted logger."""
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    return logging.getLogger(name)

